/** Khoảng giá (VNĐ) — gửi minPrice / maxPrice lên API */
export const CATALOG_PRICE_RANGES = [
  { id: "all", label: "Tất cả mức giá", min: "", max: "" },
  { id: "lt100k", label: "Dưới 100.000 ₫", min: "", max: "100000" },
  { id: "100k-500k", label: "100.000 ₫ – 500.000 ₫", min: "100000", max: "500000" },
  { id: "500k-1m", label: "500.000 ₫ – 1.000.000 ₫", min: "500000", max: "1000000" },
  { id: "1m-5m", label: "1.000.000 ₫ – 5.000.000 ₫", min: "1000000", max: "5000000" },
  { id: "gt5m", label: "Trên 5.000.000 ₫", min: "5000000", max: "" },
];

/** Tỉnh / thành — lọc theo chuỗi con trong trường địa chỉ sản phẩm */
export const VIETNAM_PROVINCES = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "TP. Hồ Chí Minh",
  "Hồ Chí Minh",
  "Huế",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
].sort((a, b) => a.localeCompare(b, "vi", { sensitivity: "base" }));

export const PRODUCT_CONDITIONS = [
  "Mới",
  "Như mới",
  "Tốt",
  "Trung bình",
  "Kém",
];
